### ISSUE TITLE
Unable to npm install

### ISSUE THREAD

**Issue by emileindik** [AppGeo/wms#15]
Getting an error when I try to `npm install wms` using node v11.6.0:

```
npm WARN deprecated protozero@1.5.1: protozero should no longer be used via npm, install instead via https://github.com/mapbox/mason

> mapnik@3.7.2 install /Users/user/Desktop/projects/reviz/server/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.7.2/node-v67-darwin-x64-Release.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.7.2 and node@11.6.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.7.2/node-v67-darwin-x64-Release.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.7.2 and node@11.6.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp) 
/bin/sh: mapnik-config: command not found
/bin/sh: mapnik-config: command not found
gyp: Call to 'mapnik-config --cflags' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp: Call to 'mapnik-config --cflags' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gypgyp  ERR! configure error 
ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/user/.nvm/versions/node/v11.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gypgyp  ERR!ERR!  stackstack     at ChildProcess.emit (events.js:188:13)
 Error: `gyp` failed with exit code: 1
gyp gypERR!  stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
ERR! stack     at ChildProcess.onCpExit (/Users/user/.nvm/versions/node/v11.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp gypERR!  ERR! stackSystem     at ChildProcess.emit (events.js:188:13)
 Darwin 17.7.0
gyp ERR!gyp  ERR!stack      at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
command "/Users/user/.nvm/versions/node/v11.6.0/bin/node" "/Users/user/.nvm/versions/node/v11.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/user/Desktop/projects/reviz/server/node_modules/mapnik/lib/binding/mapnik.node" "--module_name=mapnik" "--module_path=/Users/user/Desktop/projects/reviz/server/node_modules/mapnik/lib/binding"
gyp ERR! cwd /Users/user/Desktop/projects/reviz/server/node_modules/mapnik
gyp ERR!gyp node -v  v11.6.0
ERR!gyp  ERR!System node-gyp -v Darwin 17.7.0
 v3.8.0
gyp ERR! not okgyp 
 ERR! command "/Users/user/.nvm/versions/node/v11.6.0/bin/node" "/Users/user/.nvm/versions/node/v11.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/user/Desktop/projects/reviz/server/node_modules/mapnik/lib/binding/mapnik.node" "--module_name=mapnik" "--module_path=/Users/user/Desktop/projects/reviz/server/node_modules/mapnik/lib/binding"
gyp ERR! cwd /Users/user/Desktop/projects/reviz/server/node_modules/mapnik
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/user/.nvm/versions/node/v11.6.0/bin/node /Users/user/.nvm/versions/node/v11.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/user/Desktop/projects/reviz/server/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/Users/user/Desktop/projects/reviz/server/node_modules/mapnik/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/user/Desktop/projects/reviz/server/node_modules/mapnik/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/Users/user/.nvm/versions/node/v11.6.0/bin/node" "/Users/user/Desktop/projects/reviz/server/node_modules/mapnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/user/Desktop/projects/reviz/server/node_modules/mapnik
node-pre-gyp ERR! node -v v11.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/Users/user/.nvm/versions/node/v11.6.0/bin/node /Users/user/.nvm/versions/node/v11.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/user/Desktop/projects/reviz/server/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/Users/user/Desktop/projects/reviz/server/node_modules/mapnik/lib/binding' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mapnik@3.7.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mapnik@3.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2019-01-13T00_23_22_777Z-debug.log
```

Thanks!

**Comment by emileindik** [comment]
Solved by downgrading to node v8.15.0

**Comment by calvinmetcalf** [comment]
yeah I havn't gotten around to updating this to node 10, I probably will at some point
